### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/vacancy-notifier-service#1]
Using Spring Initializr

- [x] Spring Boot 3
- [x] Spring AMQP (RabbitMQ) module
- [x] Spring Web module (for `RestTemplate`)

**Comment by vishalsingh2972** [comment]
is this issue still open @zhukovsd ?

**Comment by zhukovsd** [comment]
@vishalsingh2972 just closed it by merging a PR. It's a training team project, no external help is needed. Thanks for your interest.
